name: Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    -
      name: Prepare - Checkout Code
      uses: actions/checkout@v3
    -
      name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    -
      name: Prepare - Build Source
      run: |
        dotnet build src/All/All.csproj \
          --configuration Debug \
          --framework net6.0
    -
      name: A - Build Documentation
      uses: nunit/docfx-action@v2.8.0
      with:
        args: docs/docfx.json
    - 
      name: B - Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
