name: Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    -
      name: Prepare - Checkout Code
      uses: actions/checkout@v3
    -
      name: Prepare - Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    -
      name: Prepare - Build Source
      run: |
        dotnet build Test.csproj \
          --configuration Release
    - 
      name: Build Documentation
      uses: nunit/docfx-action@v2.8.0
      with:
        args: docs/docfx.json
    - 
      name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
