name: Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Code
      uses: actions/checkout@v3
    -
      name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    -
      name: Build Source
      run: |
        dotnet build src/All/All.csproj \
          --configuration Debug \
          --framework net6.0
    -
      name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: src/All/bin/Debug/net6.0
  build:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
    -
      name: Download Binaries
      uses: actions/download-artifact@v3
      with:
        name: binaries
    -
      name: Build Documentation
      uses: nunit/docfx-action@v2.8.0
      with:
        args: docs/docfx.json
    -
      name: Upload Docs
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: src/docs/_site
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    -
      name: Download Docs
      uses: actions/download-artifact@v3
      with:
        name: docs
    - 
      name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: src/docs/_site
